version: '3'

services:
  node-app-container:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=one_zee
      - MONGO_INITDB_ROOT_PASSWORD=password1
    volumes:
      - mongo-db:/data/db


volumes:
  mongo-db: