version: '3'

services:
  node-app-container:
    build:
      context: .
      args: 
        - NODE_ENV=development
    volumes:
      - ./:/app
      #app crashes with this option its not supposed to
      #- /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=one_zee
      - MONGO_PASSWORD=password1
      - SESSION_SECRET=someSecretString    
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=one_zee
      - MONGO_INITDB_ROOT_PASSWORD=password1